name: Update pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby gems
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare Pages artifact
        run: |
          mkdir output

          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            cp -r _site/* output/
          else
            mkdir output/dev
            cp -r _site/* output/dev/
          fi

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
