name: Run folder to gallery

on:
  workflow_dispatch:

permissions:
  contents: write  # 🔑 This allows the workflow to push changes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python folder_to_gallery.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gallery.json
          git diff --cached --quiet || git commit -m "Update gallery.json"
          git push
